name: Pipeline CI - Sistema Bancário JAVA beta


on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build-e-testes:
        runs-on: ubuntu-latest

        steps:

        - name: checkout do código
          uses: actions/checkout@v3
    
        - name: configurando JDK 21
          uses: actions/setup-java@v3
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: maven
            
        - name: build e testes com o Maven
          run: mvn clean verify 
        
